In [1]:
import numpy as np

Creating Arrays (ndarray)

In [2]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

In [3]:
a

array([1, 2, 3])

In [4]:
b

array([[1, 2],
       [3, 4]])

Common Array Creators

In [5]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Array Properties

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
arr.shape

(2, 3)

In [12]:
arr.ndim

2

In [13]:
arr.size

6

In [14]:
arr.dtype

dtype('int64')

Indexing and Slicing

In [15]:
arr = np.array([10, 20, 30, 40])

In [16]:
arr[0]

np.int64(10)

In [17]:
arr[-1]

np.int64(40)

In [18]:
arr[1:3]

array([20, 30])

In [19]:
mat = np.array([[1, 2, 3], [4, 5, 6]])

In [20]:
mat[0, 1]

np.int64(2)

In [21]:
mat[:, 1]

array([2, 5])

In [22]:
mat[1, :]

array([4, 5, 6])

Boolean Indexing

In [23]:
arr = np.array([1, 2, 3, 4, 5])

In [24]:
arr[arr > 3]

array([4, 5])

In [25]:
arr[arr % 2 == 0]

array([2, 4])

Array Operatings (Vectorization)

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

Element-wise Operations

In [27]:
a + b

array([5, 7, 9])

In [28]:
a * b

array([ 4, 10, 18])

In [29]:
a ** 2

array([1, 4, 9])

Scalar Operations

In [30]:
a + 10

array([11, 12, 13])

In [31]:
a * 5

array([ 5, 10, 15])

Broadcasting (Very Important)

In [32]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
vec = np.array([10, 20, 30])

In [33]:
mat + vec

array([[11, 22, 33],
       [14, 25, 36]])

Mathematical Functions

In [34]:
np.sum(arr)

np.int64(15)

In [35]:
np.mean(arr)

np.float64(3.0)

In [36]:
np.std(arr)

np.float64(1.4142135623730951)

In [37]:
np.min(arr)

np.int64(1)

In [38]:
np.max(arr)

np.int64(5)

Axis Usage

In [39]:
np.sum(mat, axis=0)

array([5, 7, 9])

In [40]:
np.sum(mat, axis=1)

array([ 6, 15])

Reshaping and Manipulation

In [41]:
arr = np.arange(6)

In [42]:
arr.reshape((2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
arr.flatten

<function ndarray.flatten(order='C')>

In [44]:
arr.ravel

<function ndarray.ravel(order='C')>

In [45]:
mat.T

array([[1, 4],
       [2, 5],
       [3, 6]])

Stacking and Splitting

In [46]:
a = np.array([1, 2])
b = np.array([3, 4])

In [47]:
np.vstack((a, b))

array([[1, 2],
       [3, 4]])

In [48]:
np.hstack((a, b))

array([1, 2, 3, 4])

In [49]:
np.split(np.arange(10), 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

Copy vs View (COMMON BUG)

In [50]:
a = np.array([1, 2, 3])
b = a           # reference
c = a.copy()    # deep copy

In [51]:
b[0] = 100
print(b)

[100   2   3]


In [52]:
c[0] = 999
print(a)

[100   2   3]


Random Numbers

In [53]:
np.random.rand(3, 3)

array([[0.7807398 , 0.30394571, 0.88372272],
       [0.87949502, 0.68301439, 0.46546929],
       [0.86165053, 0.3388896 , 0.9828228 ]])

In [54]:
np.random.randn(3, 3)

array([[ 0.22129824,  0.58167474,  0.19584259],
       [ 0.56041944, -0.02473139, -0.34504571],
       [-1.41394242, -1.3778711 , -1.62964192]])

In [55]:
np.random.randint(0, 10, size=(3, 3))

array([[3, 7, 6],
       [4, 2, 3],
       [9, 2, 9]])

In [56]:
print(np.random.seed(42))

None


Linear Algebra (ML Core)

In [57]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [58]:
A @ B   # Matrix Multiplication

array([[19, 22],
       [43, 50]])

In [59]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [60]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [61]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [62]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

Statistics and Data Prep

In [63]:
data = np.array([10, 20, 30, 40])

In [64]:
# Normalization
(data - data.mean()) / data.std()

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [65]:
# Min-Max Scaling
(data - data.min()) / (data.max() - data.min())

array([0.        , 0.33333333, 0.66666667, 1.        ])