In [112]:
import numpy as np

Create a Custom Grid
- Create a 5x5 matrix where each element is equal to the sum of its rows and column index.

In [113]:
rows, cols = 5, 5
mat = np.zeros((rows, cols), dtype=int)

for i in range(rows):
    for j in range(cols):
        mat[i,j] = i + j

print(mat)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


Diagonal Matrix
- Create a 6x6 matrix where diagonal elements are 1, others 0, then multiply the diagonal by 5.

In [114]:
mat = np.eye(6) * 5
print(mat)

[[5. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 5.]]


Extract Submatrix
- Create 10x10 array with numbers from 0 to 99
- Extract the 3x3 center matrix

In [115]:
arr = np.arange(100).reshape(10, 10)
print(arr)
center = arr[3:6, 3:6]
print()
print(center)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

[[33 34 35]
 [43 44 45]
 [53 54 55]]


Normalize Random Data
- Generate a 1x20 array of random integers 50-100
- Normalize it using min-max scaling

In [116]:
data = np.random.randint(50, 101, 20)
min_max = (data - data.min()) / (data.max() - data.min())
print(min_max)

[0.35416667 0.14583333 0.33333333 0.08333333 0.91666667 0.91666667
 0.3125     0.0625     0.89583333 0.1875     0.97916667 0.77083333
 0.29166667 0.52083333 0.79166667 0.45833333 0.20833333 0.
 0.75       1.        ]


Replace Condition
- Create array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
- Replace even numbers with -1

In [117]:
arr = np.arange(1, 11)
arr[arr % 2 == 0] = -1
print(arr)

[ 1 -1  3 -1  5 -1  7 -1  9 -1]


Matrix Multiplication
- Create A = [[1, 2, 3], [4, 5, 6]] and B = [[1, 2], [3, 4], [5, 6]]
- Computer C = A x B using NumPy matrix multiplication

In [118]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = A @ B
print(C)

[[22 28]
 [49 64]]


Standardize Data
- Generate 1x15 random numbers (0-100)
- Standardize using z-score

In [119]:
data = np.random.randint(0, 101, 15)
z_score = (data - data.mean()) / data.std()
print(z_score)

[-1.54727565  0.73092162  1.08688995 -1.44048515  0.23256597 -0.7285485
  0.4817438   0.58853429  1.40726144  0.01898498 -0.90653266  1.33606777
 -0.76414533  0.83771212 -1.33369465]


Conditional Counting
- Create 1D array 1-50
- Count how many numbers are multiples of 3 but not 5

In [120]:
arr = np.arange(1, 51)
count = np.sum((arr % 3 == 0) & (arr % 5 != 0))
print(count)

13


Image Simulation
- Create a 256x256 grayscale image (values 0 -255)
- Invert the image (255 - value)

In [121]:
image = np.random.randint(0, 256, (256, 256))
inverted = 255 - image
print(image)
print()
print(inverted)

[[250 182  36 ... 190 224  74]
 [128 189 191 ... 200  13  35]
 [243 149 236 ...  90 236  84]
 ...
 [242  45  98 ... 174 147  55]
 [ 90  94 167 ... 230 176 133]
 [122 237 230 ...  92  73  64]]

[[  5  73 219 ...  65  31 181]
 [127  66  64 ...  55 242 220]
 [ 12 106  19 ... 165  19 171]
 ...
 [ 13 210 157 ...  81 108 200]
 [165 161  88 ...  25  79 122]
 [133  18  25 ... 163 182 191]]


Covariance Matrix
- Generate 3 random features (10 samples each)
- Compute covariance matrix without using pandas

In [122]:
X = np.random.rand(10, 3)
cov_matrix = np.cov(X, rowvar=False)
print(cov_matrix)

[[0.08725347 0.00498162 0.01314316]
 [0.00498162 0.07532103 0.01337218]
 [0.01314316 0.01337218 0.09175674]]
